services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  influxdb:
    image: influxdb
    ports:
      - 8086:8086
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
