# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    
