apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkiver-graphql-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arkiver-graphql-server
  template:
    metadata:
      labels:
        app: arkiver-graphql-server
    spec:
      containers:
        - name: arkiver-graphql-server
          image: arkiver-graphql-server
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          imagePullPolicy: Never
          env:
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: SUPABASE_SERVICE_KEY
            - name: MONGO_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: MONGO_CONNECTION
            - name: INFLUX_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: INFLUX_URL
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: INFLUX_ADMIN_TOKEN
            - name: INFLUX_ORG
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: INFLUX_ORG
            - name: INFLUX_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: INFLUX_BUCKET
            - name: SERVER_REDIS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: SERVER_REDIS_HOSTNAME
            - name: SERVER_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: SERVER_REDIS_PORT
