apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-influx
  template:
    metadata:
      labels:
        app: local-influx
    spec:
      containers:
      - name: local-influx
        image: influxdb:latest
        ports:
        - containerPort: 8086
          name: influx
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: setup
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: admin
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: password123
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: arkiver
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: arkiver
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: admin
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: 1h