apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-graphql-server
spec:
  serviceName: "redis-graphql-server"
  replicas: 1
  selector:
    matchLabels:
      app: redis-graphql-server
  template:
    metadata:
      labels:
        app: redis-graphql-server
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-graphql-server-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-graphql-server-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
